# This file defines and runs multi-container Docker applications using Docker Compose.

services:
  frontend:
    container_name: neuroassess-frontend # Sets a custom name for the frontend container
    build:
      context: ./client # Path to the client folder (React app)
      dockerfile: Dockerfile # Dockerfile to use (in client folder)
    ports:
      - "3000:3000" # Maps local port 3000 to container port 3000 (Vite dev server)
    env_file:
      - ./client/.env # Loads environment variables from client/.env into container
    volumes:
      - ./client:/app # Mounts the local client folder to /app in container for live code sync
      - /app/node_modules # Prevents host node_modules from interfering with container's
    depends_on:
      - backend # Ensures backend starts before frontend if needed
    command: npm run dev # Command to run inside container (starts Vite dev server)

  backend:
    container_name: neuroassess-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
